language: android
dist: trusty
before_install:
  - chmod +x gradlew
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra

env:
  global:
    - ADB_INSTALL_TIMEOUT=8


script:
  - ./gradlew clean assembleDebug testDebug