language: android
dist: trusty
android:
  components:
    - build-tools-28.0.2
    - android-28
    - extra

env:
  global:
    - ADB_INSTALL_TIMEOUT=8


script:
  - ./gradlew clean assembleDebug assembleRelease testDebug